import { describe, expect, it } from "vitest";
// `@/*` maps to `src/*` only, and the subject here is local-stack tooling under `scripts/` —
// see test-plan.md §6.1 on why its test still sits in tests/lib/ beside the suite's other
// pure-function files rather than in a tests/scripts/ folder holding one file.
import {
  KONG_KEEPALIVE_ENV,
  KONG_KEEPALIVE_STOCK,
  buildRunArgs,
  containerNames,
  isKeepAlivePoolDisabled,
  parseKongEnv,
} from "../../scripts/kong-keepalive.ts";

// Everything about the Kong recreation that can be decided WITHOUT touching Docker. The
// runner beside it (./disable-kong-keepalive.ts) removes the stack's only proxy and puts it
// back, so this half has veto power over whether the developer's stack comes up at all —
// which is the whole reason it is a separate, assertable module rather than a shell
// incantation (the same split scripts/schema-drift.ts already uses, for the same reason).
//
// The Docker calls themselves are NOT covered here and cannot be: they are live operations
// against a running container. Their evidence is the recorded run in the change's
// verification.md plus the script's own refusal to report success on anything it did not
// read back from `.kong_env`.

/**
 * The keep-alive triple as Kong really dumps it, verbatim from the running container on
 * 2026-08-01 — comment banner, unrelated settings interleaved, `key = value` spacing, and
 * the three keys NOT adjacent (`ssl_cert_key` sits between max_requests and idle_timeout).
 * Fabricating a tidy three-line fixture would have quietly tested a format Kong never emits.
 */
const REAL_DUMP_STOCK = `# *************************
# * DO NOT EDIT THIS FILE *
# *************************
# This configuration file is auto-generated. If you want to modify
# the Kong configuration please edit/create the original \`kong.conf\`
# file. Any modifications made here will be lost.

go_plugins_dir = off
nginx_conf = /usr/local/kong/nginx.conf
mem_cache_size = 128m
upstream_keepalive_pool_size = 60
upstream_keepalive_max_requests = 100
ssl_cert_key = /home/kong/localhost.key
upstream_keepalive_idle_timeout = 60
port_maps = 54321:8000
proxy_listen = 0.0.0.0:8000 reuseport backlog=16384
`;

/** The same dump as it must read once the lever has been adopted. */
const REAL_DUMP_APPLIED = REAL_DUMP_STOCK.replace(
  "upstream_keepalive_pool_size = 60",
  "upstream_keepalive_pool_size = 0",
);

describe("parseKongEnv", () => {
  // The adoption oracle. `docker run -e …` always "succeeds"; the only thing that separates
  // "Kong took the setting" from "Kong ignored an env var it does not recognise" is Kong's
  // own dump of every resolved setting, so this parse is what the whole unsupported
  // operation rests on.
  it("reads the keep-alive triple out of Kong's own settings dump", () => {
    expect(parseKongEnv(REAL_DUMP_STOCK)).toEqual({
      poolSize: 60,
      maxRequests: 100,
      idleTimeout: 60,
    });
  });

  it("reads the pool size back as 0 once the lever has been adopted", () => {
    expect(parseKongEnv(REAL_DUMP_APPLIED)).toEqual({
      poolSize: 0,
      maxRequests: 100,
      idleTimeout: 60,
    });
  });

  // A key that is absent is NOT a key that is zero, and conflating the two is the false
  // green this module exists to prevent: a Kong version that renamed the setting would dump
  // no `upstream_keepalive_pool_size` at all, and a parser defaulting to 0 would report the
  // lever as adopted while nothing had changed.
  it("reports a missing key as null rather than as zero", () => {
    expect(parseKongEnv("mem_cache_size = 128m\n")).toEqual({
      poolSize: null,
      maxRequests: null,
      idleTimeout: null,
    });
  });

  // `#` lines are the first seven lines of every real dump, and one of them contains the
  // word `configuration` — a parser splitting on `=` without skipping comments would read
  // the banner as settings.
  it("ignores the comment banner Kong writes above the settings", () => {
    expect(parseKongEnv("# upstream_keepalive_pool_size = 999\nupstream_keepalive_pool_size = 0\n").poolSize).toBe(0);
  });
});

describe("isKeepAlivePoolDisabled", () => {
  it("is true only when the pool size read back is exactly 0", () => {
    expect(isKeepAlivePoolDisabled(parseKongEnv(REAL_DUMP_APPLIED))).toBe(true);
  });

  // THE POSITIVE CONTROL for the predicate: without a case proving it answers false on the
  // stock dump, a predicate hardcoded to `true` satisfies the case above — and this
  // predicate is what the runner uses to decide it may exit 0.
  it("is false on the stock dump, so the script cannot report success on an unmodified Kong", () => {
    expect(isKeepAlivePoolDisabled(parseKongEnv(REAL_DUMP_STOCK))).toBe(false);
  });

  it("is false when the key is absent altogether", () => {
    expect(isKeepAlivePoolDisabled({ poolSize: null, maxRequests: null, idleTimeout: null })).toBe(false);
  });
});

describe("containerNames", () => {
  // Both names are derived from `project_id` in supabase/config.toml, and the container name
  // is what `docker rm -f` targets — deriving it wrongly would remove nothing, or something
  // else entirely.
  it("derives the Kong container and network names from the project id", () => {
    expect(containerNames("10x-astro-starter")).toEqual({
      container: "supabase_kong_10x-astro-starter",
      network: "supabase_network_10x-astro-starter",
    });
  });
});

/**
 * The running Kong container's real runtime spec, read off the live stack on 2026-08-01 and
 * transcribed field for field — including the shapes that are easy to get wrong: Docker
 * reports healthcheck durations in **nanoseconds**, `PortBindings` values are arrays of
 * objects with an empty `HostIp`, and the network aliases live under the network's own key.
 *
 * `.Config.Cmd` is deliberately absent from this type, because on the real container it is
 * **null**: the CLI overrode the ENTRYPOINT at create time with a 15 KB `sh -c` heredoc that
 * writes kong.yml, the nginx template and a TLS keypair before exec'ing Kong. That override
 * lives on the container and in no image, which is exactly why the runner commits the
 * container first — the committed image carries the heredoc, so the replacement needs no
 * command and no `--entrypoint` of its own.
 */
const REAL_SPEC = {
  name: "supabase_kong_10x-astro-starter",
  image: "supabase-kong-keepalive-10x-astro-starter:latest",
  user: "kong",
  labels: {
    "com.docker.compose.project": "10x-astro-starter",
    "com.supabase.cli.project": "10x-astro-starter",
    maintainer: "Kong <support@konghq.com>",
  },
  env: [
    "KONG_DATABASE=off",
    "KONG_DECLARATIVE_CONFIG=/home/kong/kong.yml",
    "KONG_DNS_ORDER=LAST,A,CNAME",
    "KONG_PLUGINS=request-transformer,cors",
    "KONG_PORT_MAPS=54321:8000",
    "KONG_NGINX_PROXY_PROXY_BUFFER_SIZE=160k",
    "KONG_NGINX_PROXY_PROXY_BUFFERS=64 160k",
    "KONG_NGINX_WORKER_PROCESSES=1",
    "KONG_SSL_CERT=/home/kong/localhost.crt",
    "KONG_SSL_CERT_KEY=/home/kong/localhost.key",
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "ASSET=ce",
    "KONG_VERSION=2.8.1",
  ],
  restartPolicy: "unless-stopped",
  portBindings: { "8000/tcp": [{ HostIp: "", HostPort: "54321" }] },
  network: "supabase_network_10x-astro-starter",
  aliases: ["kong", "api.supabase.internal"],
  healthcheck: {
    Test: ["CMD-SHELL", "kong health"],
    Interval: 10_000_000_000,
    Timeout: 10_000_000_000,
    Retries: 10,
  },
};

/**
 * A SECOND container spec, wholly fabricated — no value here appears on this machine's stack.
 *
 * It exists because every case below that reads `REAL_SPEC` is blind to the one property the
 * module's contract names first: that `buildRunArgs` reproduces the container **from the
 * inspected spec rather than from literals**. `REAL_SPEC`'s values ARE the literals a
 * hardcoding implementation would reach for, so an assertion against it passes either way.
 * Measured, not argued (C10X-39 impl-review F1): replacing the `Object.entries(spec.labels)`
 * loop in `buildRunArgs` with three hardcoded `--label` pushes left the file **0 of 18 red**.
 *
 * The concrete cost of that blindness is the failure the label case below says it exists to
 * prevent, one clone over: a developer whose `supabase/config.toml` carries a different
 * `project_id` gets a container missing THEIR `com.supabase.cli.project`, which `supabase
 * stop` then orphans — and it collides on the name at the next `supabase start`.
 *
 * Same shape as tests/lib/config-status.test.ts, where the real env-derived constant appears
 * in no assertion for the same reason: a fixture you fabricate is the only one that can tell
 * "read from the input" apart from "happens to match this machine".
 */
const OTHER_SPEC = {
  name: "supabase_kong_other-project",
  image: "supabase-kong-keepalive-other-project:latest",
  user: "nobody",
  labels: {
    "com.docker.compose.project": "other-project",
    "com.supabase.cli.project": "other-project",
  },
  env: ["KONG_DATABASE=off", "ASSET=oss"],
  restartPolicy: "always",
  portBindings: { "8000/tcp": [{ HostIp: "", HostPort: "64321" }] },
  network: "supabase_network_other-project",
  aliases: ["kong", "gateway.internal"],
  healthcheck: {
    Test: ["CMD-SHELL", "kong health"],
    Interval: 5_000_000_000,
    Timeout: 2_000_000_000,
    Retries: 3,
  },
};

describe("buildRunArgs", () => {
  // Both labels carry `project_id`, and both are load-bearing rather than cosmetic: a
  // recreated container missing them is orphaned by `supabase stop` — it survives, keeps
  // port 54321, and then collides on the name at the next `supabase start`. That failure
  // surfaces days later as "my stack will not start" with nothing pointing back here.
  it("replicates both project labels, so `supabase stop` still owns the container", () => {
    const args = buildRunArgs(REAL_SPEC);

    expect(args).toContain("--label");
    expect(args).toContain("com.supabase.cli.project=10x-astro-starter");
    expect(args).toContain("com.docker.compose.project=10x-astro-starter");
  });

  // Every other container in the stack reaches the proxy by alias, not by container name.
  // Dropping `api.supabase.internal` leaves a Kong that is up, healthy, and unreachable from
  // the services that need it — a green health check over a broken stack.
  it("rejoins the network under both aliases", () => {
    const args = buildRunArgs(REAL_SPEC);

    expect(args).toContain("--network");
    expect(args).toContain("supabase_network_10x-astro-starter");
    expect(args).toContain("kong");
    expect(args).toContain("api.supabase.internal");
  });

  // The whole point of the exercise. Last among the `-e` flags so a duplicate key from the
  // source spec cannot win — Docker takes the LAST occurrence.
  it("appends the lever after every inherited variable", () => {
    const args = buildRunArgs(REAL_SPEC);
    const envValues = args.filter((_, i) => args[i - 1] === "-e");

    expect(envValues.at(-1)).toBe("KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0");
  });

  it("carries every inherited environment variable through untouched", () => {
    const args = buildRunArgs(REAL_SPEC);
    const envValues = args.filter((_, i) => args[i - 1] === "-e");

    for (const original of REAL_SPEC.env) expect(envValues).toContain(original);
  });

  // Port, user, restart policy and the healthcheck. The durations are the trap: Docker
  // reports them in nanoseconds and `docker run` accepts a duration STRING, so passing the
  // inspected number through unconverted yields `--health-interval 10000000000`, which is
  // ~317 years — a container that is `starting` forever and never `healthy`, i.e. the
  // runner's health wait times out and the restore path fires over a working Kong.
  it("reproduces the port binding, user, restart policy and healthcheck", () => {
    const args = buildRunArgs(REAL_SPEC).join(" ");

    expect(args).toContain("-p 54321:8000");
    expect(args).toContain("--user kong");
    expect(args).toContain("--restart unless-stopped");
    expect(args).toContain("--health-cmd kong health");
    expect(args).toContain("--health-interval 10s");
    expect(args).toContain("--health-timeout 10s");
    expect(args).toContain("--health-retries 10");
  });

  // AN ABSENCE, which is why it needs a case of its own: every assertion above checks what
  // IS in the vector and none of them can see a command that crept back in. Docker would
  // append such a command to the committed `sh -c` heredoc as ignored `$0 $1 …` args — the
  // heredoc would still run, the container would still come up, `.kong_env` would still read
  // 0, and the script's own verification would pass while the vector pinned a dead
  // component. A false green on the design rather than on the setting.
  it("ends at the image reference — no trailing command, no --entrypoint", () => {
    const args = buildRunArgs(REAL_SPEC);

    expect(args.at(-1)).toBe("supabase-kong-keepalive-10x-astro-starter:latest");
    expect(args).not.toContain("--entrypoint");
  });

  // THE POSITIVE CONTROL for the module's first contract — "reproduce from the INSPECTED
  // spec, not from literals" — and it is the only case here that can tell those two apart.
  // Every assertion above reads `REAL_SPEC`, whose values are exactly the literals a
  // hardcoding implementation would use, so all of them pass over one. Measured rather than
  // reasoned about (C10X-39 impl-review F1): hardcoding the three `--label` pushes in
  // `buildRunArgs` left the file 0 of 18 red. This case fabricates every value instead, so a
  // vector built from anything other than its argument fails it.
  it("builds from the inspected spec, not from this machine's literals", () => {
    const args = buildRunArgs(OTHER_SPEC);
    const joined = args.join(" ");

    // Nothing from REAL_SPEC may survive into a vector built from a different container.
    expect(joined).not.toContain("10x-astro-starter");

    expect(args).toContain("com.supabase.cli.project=other-project");
    expect(args).toContain("com.docker.compose.project=other-project");
    expect(args).toContain("supabase_network_other-project");
    expect(args).toContain("gateway.internal");
    expect(joined).toContain("-p 64321:8000");
    expect(joined).toContain("--user nobody");
    expect(joined).toContain("--restart always");
    // The nanosecond→duration conversion has to track the spec too, not emit `10s` by rote.
    expect(joined).toContain("--health-interval 5s");
    expect(joined).toContain("--health-timeout 2s");
    expect(joined).toContain("--health-retries 3");
    expect(args.at(-1)).toBe("supabase-kong-keepalive-other-project:latest");
  });

  // NOT a positive control, despite what this comment used to claim (corrected by C10X-39's
  // impl-review, F1): `toEqual` between two calls of the same function is trivially satisfied
  // by a `buildRunArgs` returning one fixed vector, since both sides are then that same
  // vector. What it genuinely pins is idempotency, which is its own claim worth keeping —
  // re-running the script inspects a container that ALREADY carries the lever, so the
  // pass-through must strip it and the single appended copy must leave the vector
  // byte-identical, or re-application would accumulate a second `-e` on every run.
  it("is idempotent: a spec that already carries the lever produces the identical vector", () => {
    const alreadyApplied = {
      ...REAL_SPEC,
      env: [...REAL_SPEC.env, "KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0"],
    };

    expect(buildRunArgs(alreadyApplied)).toEqual(buildRunArgs(REAL_SPEC));
  });

  // Two callers need a container at the STOCK pool size, and both are failure-adjacent: the
  // runner's restore path after a failed recreation, and Phase 5's control matrix, which has
  // to reproduce the flake at 60 for the fixed matrix's silence to mean anything.
  //
  // **Overriding is not the same as omitting, and the difference was measured rather than
  // reasoned about.** `docker commit` bakes `Config.Env` into the image, so once the runner
  // has committed an ALREADY-recreated container the image itself carries
  // `KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0` — and a vector that merely leaves the `-e` out
  // inherits it. Observed on the live stack on 2026-08-01: the "lever-less" restore came up
  // reading `upstream_keepalive_pool_size = 0` while the script printed "WITHOUT the fix".
  // Harmless for the restore; fatal for the control, which would have produced no drops and
  // been recorded as *inconclusive* — discarding a real result because of a tooling bug.
  //
  // Hence there is no "emit nothing" option at all: the caller always states the pool size it
  // wants, which makes the trap unrepresentable rather than merely documented.
  it("OVERRIDES the pool size for a stock container rather than omitting the variable", () => {
    const committedFromLevered = {
      ...REAL_SPEC,
      env: [...REAL_SPEC.env, "KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0"],
    };

    const args = buildRunArgs(committedFromLevered, KONG_KEEPALIVE_STOCK);
    const envValues = args.filter((_, i) => args[i - 1] === "-e");

    // Present, last, and exactly once — a second copy would let the image's baked-in 0 be
    // ambiguous about which wins.
    expect(envValues.at(-1)).toBe("KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=60");
    expect(envValues.filter((v) => v.startsWith("KONG_UPSTREAM_KEEPALIVE_POOL_SIZE="))).toHaveLength(1);
    // …and it is still a complete, runnable container, not a stripped-down one.
    expect(args).toContain("com.supabase.cli.project=10x-astro-starter");
    expect(args.at(-1)).toBe("supabase-kong-keepalive-10x-astro-starter:latest");
  });
});

describe("KONG_KEEPALIVE_ENV", () => {
  // Pinned as a value rather than described in prose: this exact key is the community
  // workaround from Kong issue #11160, and Kong silently ignores an env var it does not
  // recognise, so a typo here is invisible except through `.kong_env`.
  it("is the upstream pool-size lever set to zero", () => {
    expect(KONG_KEEPALIVE_ENV).toEqual({ key: "KONG_UPSTREAM_KEEPALIVE_POOL_SIZE", value: "0" });
  });

  // Kong 2.8.1's own default, pinned as a value because the whole point of the stock vector
  // is to reproduce the UNFIXED stack faithfully — a wrong number here would make Phase 5's
  // control matrix a measurement of some third configuration nobody runs.
  it("has a stock counterpart carrying Kong's default pool size", () => {
    expect(KONG_KEEPALIVE_STOCK).toEqual({ key: KONG_KEEPALIVE_ENV.key, value: "60" });
  });
});
