// The whole "did this change pass review?" decision, as a pure function over the agent's
// JSON result and the committed criteria list. No filesystem, no network, no console — all
// of that lives in the runner beside this file (./run-review-verdict.ts), which is what
// makes this half testable with ordinary fixtures.
//
// The split is not stylistic here, it is load-bearing: tests/lib/review-verdict.test.ts
// imports this module, and vitest.config.ts pins `sequence: { shuffle: true }`, so any CLI
// code running at module scope would execute against vitest's argv at a random point in the
// suite — a failure that would first be seen as a flake. Same pure/runner pattern as
// ./schema-drift.ts ↔ ./check-schema-drift.ts and ./db-cleanup.ts ↔ ./run-db-cleanup.ts.
//
// Why both files sit in `scripts/` rather than `src/`: the runner prints, and
// tests/lib/no-logging.test.ts fails the build on any `console.*` under `src/`. It also keeps
// their import a sibling instead of the deep relative path AGENTS.md's first Hard Rule
// forbids (the `@/*` alias maps to `src/*` only and does not resolve under type stripping).

/**
 * The sensitivity of the whole gate, as ONE named number — and the only place it exists in
 * this repository.
 *
 * It deliberately does NOT appear in the system prompt or in any criterion description
 * (`agents/review/review-schema.ts`). A threshold woven into the prompt changes the model's
 * INPUT every time sensitivity is tuned, so it changes what the agent is asked to judge at
 * the same moment as what we do with the answer — and that invalidates the before/after
 * comparison this change's exit condition stands on.
 */
/**
 * The ends of the scale every criterion is scored on. Exported so the test can pin them rather
 * than restate them: they are a CONTRACT with `review-schema.ts`'s field descriptions, which is
 * the only other place the range is expressed — and that place cannot enforce it.
 */
export const SCORE_MIN = 1;
export const SCORE_MAX = 10;

export const SCORE_THRESHOLD = 5;

/**
 * One entry of `agents/review/criteria.json` — DATA generated by the agent, never its code.
 *
 * `agents/**` sits outside this project's tsconfig, ESLint and vitest on purpose, so the
 * second copy of the criteria list that would otherwise live here does not exist at all:
 * there is nothing to drift. The generator (`npm --prefix agents/review run criteria`) and
 * the `git diff --exit-code` gate in the composite action close that pair mechanically.
 */
export interface Criterion {
  /** Name of the SCORE field in the agent's result JSON. */
  readonly key: string;
  /** Name of the RATIONALE field in the agent's result JSON. */
  readonly noteKey: string;
  /** Polish label for the PR comment. */
  readonly label: string;
  /** `true` → the score may be `null` ("does not apply"). Exactly two criteria are. */
  readonly conditional: boolean;
}

/** One criterion as read out of the result: the row the comment table renders. */
export interface ScoreRow {
  readonly key: string;
  readonly label: string;
  /**
   * `null` means "does not apply" — a value DISTINGUISHABLE from every score, never 0 and
   * never an absent field. A 10 for "no risk here" would inflate a change that touched no
   * write path above one that touched it and handled it properly; a 1 would punish a risk
   * that does not exist.
   */
  readonly score: number | null;
  readonly note: string;
}

/** The agent's result, once every field the contract promises has been checked. */
export interface AgentReview {
  readonly verdict: "pass" | "fail";
  readonly summary: string;
  /** In `criteria.json` order — the order the comment table must render. */
  readonly scores: readonly ScoreRow[];
}

export interface FailingCriterion {
  readonly key: string;
  readonly label: string;
  readonly score: number;
  readonly note: string;
}

export interface SkippedCriterion {
  readonly key: string;
  readonly label: string;
  readonly note: string;
}

export interface Decision {
  readonly verdict: "pass" | "fail";
  /** Scored below the threshold, in criteria order. Empty on `pass`. */
  readonly failing: readonly FailingCriterion[];
  /** Answered `null` ("does not apply"). Never influences the verdict in either direction. */
  readonly skipped: readonly SkippedCriterion[];
}

export interface DecideVerdictInput {
  /** The agent's result JSON, exactly as parsed off disk — validated here, not assumed. */
  readonly review: unknown;
  /** The committed criteria list; its ORDER is the contract for everything downstream. */
  readonly criteria: readonly Criterion[];
  readonly threshold: number;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Read the agent's result against the criteria list, refusing anything that is not the
 * shape the contract promises.
 *
 * **A missing criterion throws rather than being skipped**, and that is the whole reason
 * this function exists instead of an inline `review[key] ?? null`: treating an absent field
 * as "does not apply" would make "the agent forgot to score this" byte-identical to "this
 * criterion genuinely has no bearing on the diff". The requirements forbid exactly that
 * confusion, and the same reasoning is why `null` on a NON-conditional criterion is a
 * refusal too — the schema declares those seven as plain numbers, so a `null` there is a
 * broken contract, not a judgement.
 *
 * The agent validates its own output with zod before printing it, so in the normal path
 * nothing here can fire. That is not a reason to drop the checks: this half also runs on a
 * file handed to it by the workflow, and a gate that trusts its input is a gate that goes
 * green on its own malfunction.
 */
export function parseReview(review: unknown, criteria: readonly Criterion[]): AgentReview {
  if (!isRecord(review)) {
    throw new Error("Wynik agenta nie jest obiektem JSON.");
  }

  if (review.verdict !== "pass" && review.verdict !== "fail") {
    throw new Error(
      `Wynik agenta nie niesie werdyktu \`pass\`/\`fail\` (otrzymano: ${JSON.stringify(review.verdict)}).`,
    );
  }

  if (typeof review.summary !== "string") {
    throw new Error("Wynik agenta nie niesie pola `summary` typu string.");
  }

  const scores = criteria.map((criterion): ScoreRow => {
    if (!(criterion.key in review)) {
      throw new Error(
        `Wynik agenta nie zawiera kryterium \`${criterion.key}\` („${criterion.label}”). ` +
          `Brak oceny NIE jest „nie dotyczy” — to niedomknięty kontrakt wyjścia.`,
      );
    }
    if (!(criterion.noteKey in review)) {
      throw new Error(
        `Wynik agenta nie zawiera uzasadnienia \`${criterion.noteKey}\` dla kryterium „${criterion.label}”.`,
      );
    }

    const rawScore = review[criterion.key];
    const rawNote = review[criterion.noteKey];

    if (typeof rawNote !== "string") {
      throw new Error(`Uzasadnienie \`${criterion.noteKey}\` nie jest stringiem.`);
    }

    if (rawScore === null) {
      if (!criterion.conditional) {
        throw new Error(
          `Kryterium \`${criterion.key}\` („${criterion.label}”) nie jest warunkowe, ` +
            `więc \`null\` („nie dotyczy”) jest tu złamaniem kontraktu, a nie oceną.`,
        );
      }
      return { key: criterion.key, label: criterion.label, score: null, note: rawNote };
    }

    if (typeof rawScore !== "number" || !Number.isFinite(rawScore)) {
      throw new Error(`Ocena \`${criterion.key}\` nie jest liczbą (otrzymano: ${JSON.stringify(rawScore)}).`);
    }

    // The range is enforced HERE because there is nowhere else it can be. `review-schema.ts`
    // deliberately omits `minimum`/`maximum` — structured output rejects them on an integer
    // type — so the 1-10 scale is steered by the field DESCRIPTION alone, which is guidance to
    // a model, not a contract. Unchecked, a 42 renders as "42/10" in a comment on a public pull
    // request and a -3 quietly forces `fail`. The argument is the same one already used to
    // refuse `null` on a non-conditional criterion: a value outside the contract is a broken
    // output contract, not an unusual opinion.
    if (rawScore < SCORE_MIN || rawScore > SCORE_MAX) {
      throw new Error(
        `Ocena \`${criterion.key}\` („${criterion.label}”) wynosi ${rawScore}, a skala to ${SCORE_MIN}-${SCORE_MAX}. ` +
          "Schemat nie egzekwuje zakresu (structured output odrzuca minimum/maximum), więc pilnuje go ta walidacja.",
      );
    }

    return { key: criterion.key, label: criterion.label, score: rawScore, note: rawNote };
  });

  return { verdict: review.verdict, summary: review.summary, scores };
}

/**
 * The verdict rule from the requirements, and nothing else.
 *
 * `fail` when the agent's own overall verdict is `fail` **OR** when any single criterion
 * scored below the threshold. The two sources are an ALTERNATIVE, never a conjunction: the
 * agent may spot a problem it could not push into any one criterion, and conversely it may
 * hand out a 1 and still summarise the change kindly.
 *
 * **No average is computed, and that is a decision rather than an omission.** An average
 * hides one catastrophic dimension among eight good ones — and in this repository that one
 * dimension is, measurably, security or a swallowed error (five `…-swallowed` folders in
 * `context/archive/` from a single week). Averaging turns a veto into one vote in a ballot
 * the other eight always win.
 */
export function decideVerdict({ review, criteria, threshold }: DecideVerdictInput): Decision {
  const { verdict: agentVerdict, scores } = parseReview(review, criteria);

  const failing: FailingCriterion[] = [];
  const skipped: SkippedCriterion[] = [];

  for (const row of scores) {
    if (row.score === null) {
      // Excluded from the aggregation in BOTH directions: a skipped criterion is neither an
      // argument for `pass` nor for `fail`. It is still reported, because a silently dropped
      // row would be indistinguishable from a criterion the agent forgot.
      skipped.push({ key: row.key, label: row.label, note: row.note });
      continue;
    }
    if (row.score < threshold) {
      failing.push({ key: row.key, label: row.label, score: row.score, note: row.note });
    }
  }

  return {
    verdict: agentVerdict === "fail" || failing.length > 0 ? "fail" : "pass",
    failing,
    skipped,
  };
}
