// Retries ONE class of failure — the local stack's Kong→PostgREST keep-alive drop — and
// nothing else. Registered as a `setupFiles` entry (vitest.config.ts), so it installs once
// per worker, before any test module of that file is imported.
//
// WHY THIS EXISTS. Measured on 2026-07-30 while enabling `sequence.shuffle` (C10X-32): the
// full suite went red on roughly 10-15% of runs, a DIFFERENT random case each time, none of
// them reproducible in isolation or at its own seed. Kong names the mechanism:
//
//   [error] upstream prematurely closed connection while reading response header from
//   upstream, request: "POST /rest/v1/deck?select=id%2Cpublic_id",
//   upstream: "http://172.18.0.5:3000/deck?…"
//   "POST /rest/v1/deck?select=id%2Cpublic_id HTTP/1.1" 502 75 "-" "node"
//
// Kong (nginx) pools keep-alive connections to PostgREST and holds them idle longer than
// PostgREST's warp server keeps them open. Between two `npm test` runs those connections sit
// idle — the observed 502s follow a ~28 s gap in Kong's access log — so the first request
// after the gap is sent down a socket the upstream has already closed. It is a transport
// race in the dev stack, NOT a defect in this repo and NOT an ordering problem: the red rate
// is the same with shuffle on and off (3/20 either way, paired same-session control), is
// unchanged by restarting `rest`+`kong`, and is unchanged by cutting file parallelism from
// ~18 workers to 4. Neither `supabase/config.toml` nor PostgREST exposes the keep-alive
// timeout that would fix it at the source, and Kong's config is generated by the CLI.
//
// WHY RETRYING IS SAFE HERE, INCLUDING FOR A POST. nginx reports this error after it has
// written the request and then read EOF while waiting for the response *header*. A PostgREST
// that had processed and committed the statement would have sent that header first, and the
// only way to commit without one is a crash — which did not happen (the container reports
// `RestartCount=0` and logs nothing across every observed 502). So the request never
// executed, which is exactly what the failures showed from the other side: every red found
// the row absent ("Setup failed: card … was never written"), never duplicated. The residual
// risk of a retried write landing twice is therefore accepted deliberately rather than
// overlooked — and it is observable, because a double write in this suite surfaces loudly as
// a `deck_user_name_unique` 409 or a count assertion, not as a false green.
//
// THE PREDICATE IS DELIBERATELY NARROW — widen it only with the same kind of evidence:
//   - status 502 AND Kong's own upstream wording. No other status is retried: a 500 from an
//     endpoint, a 409, a 4xx refusal and a PostgREST error body are all real signals this
//     suite asserts on, and retrying any of them would mask a genuine failure.
//   - the local stack only (preflight already guarantees the host is 127.0.0.1/localhost).
//   - string or absent bodies only. A `Request` instance or a stream body cannot be replayed
//     without consuming it, so those are passed through untouched rather than guessed at.
//
// It composes with the one file that doubles `fetch`
// (tests/generation/failure-path.test.ts, test-plan §6.9): setup files run first, so the
// `realFetch` that file captures at module scope IS this wrapper, and the Supabase calls it
// delegates get the retry while its own synthetic OpenRouter responses — built above this
// layer, and never a 502 — never reach it.
//
// NOT covered: `globalSetup` (preflight, accounts) runs in a separate process this file
// cannot reach. Left alone on purpose — a 502 there aborts the whole run with its own
// message instead of producing a false green, which is the failure mode that matters.

/** Kong's wording for "the upstream closed the connection before answering". */
const KONG_UPSTREAM_FAILURE = "An invalid response was received from the upstream server";

/** One original attempt plus at most two replays. */
const MAX_ATTEMPTS = 3;

/** Long enough for Kong to open a fresh upstream socket, short enough to be invisible. */
const BACKOFF_MS = 25;

const passthrough = globalThis.fetch;

function isLocalStack(url: string): boolean {
  try {
    const { hostname } = new URL(url);
    return hostname === "127.0.0.1" || hostname === "localhost";
  } catch {
    // A relative or malformed URL is not the local stack as far as this wrapper is concerned.
    return false;
  }
}

/** True only for a request whose body can be replayed verbatim. */
function isReplayable(input: RequestInfo | URL, init: RequestInit | undefined): boolean {
  if (input instanceof Request) return false;
  const body = init?.body;
  return body === undefined || body === null || typeof body === "string";
}

async function isKongUpstreamFailure(response: Response): Promise<boolean> {
  try {
    // `clone()` so the caller still gets an unread body when this turns out NOT to be the
    // flake and the response is handed back as-is.
    return (await response.clone().text()).includes(KONG_UPSTREAM_FAILURE);
  } catch {
    return false;
  }
}

globalThis.fetch = async function retryingFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  let response = await passthrough(input, init);

  const url = input instanceof Request ? input.url : String(input);
  if (!isLocalStack(url) || !isReplayable(input, init)) return response;

  for (let attempt = 1; attempt < MAX_ATTEMPTS; attempt++) {
    if (response.status !== 502 || !(await isKongUpstreamFailure(response))) return response;
    await new Promise((resolve) => setTimeout(resolve, BACKOFF_MS * attempt));
    response = await passthrough(input, init);
  }
  // Three upstream failures in a row is no longer a keep-alive race; hand the 502 back and
  // let the assertion that was in flight report it.
  return response;
};
