// Retries ONE class of failure — the local stack's Kong→PostgREST keep-alive drop — and
// nothing else. Registered as a `setupFiles` entry (vitest.config.ts), so it runs once per
// TEST FILE — not once per worker — before that file's modules are imported. The install is
// guarded by a sentinel for exactly that reason; see the bottom of this file.
//
// WHY THIS EXISTS. Measured on 2026-07-30 while enabling `sequence.shuffle` (C10X-32): the
// full suite went red on roughly 10-15% of runs, a DIFFERENT random case each time, none of
// them reproducible in isolation or at its own seed. Kong names the mechanism:
//
//   [error] upstream prematurely closed connection while reading response header from
//   upstream, request: "POST /rest/v1/deck?select=id%2Cpublic_id",
//   upstream: "http://172.18.0.5:3000/deck?…"
//   "POST /rest/v1/deck?select=id%2Cpublic_id HTTP/1.1" 502 75 "-" "node"
//
// Kong (nginx) pools keep-alive connections to PostgREST and holds them idle longer than
// PostgREST's warp server keeps them open. Between two `npm test` runs those connections sit
// idle — the observed 502s follow a ~28 s gap in Kong's access log — so the first request
// after the gap is sent down a socket the upstream has already closed. It is a transport
// race in the dev stack, NOT a defect in this repo and NOT an ordering problem: the red rate
// is the same with shuffle on and off (3/20 either way, paired same-session control), is
// unchanged by restarting `rest`+`kong`, and is unchanged by cutting file parallelism from
// ~18 workers to 4. Neither `supabase/config.toml` nor PostgREST exposes the keep-alive
// timeout that would fix it at the source, and Kong's config is generated by the CLI.
//
// WHY RETRYING IS SAFE HERE, INCLUDING FOR A POST. nginx reports this error after it has
// written the request and then read EOF while waiting for the response *header*. A PostgREST
// that had processed and committed the statement would have sent that header first, and the
// only way to commit without one is a crash — which did not happen (the container reports
// `RestartCount=0` and logs nothing across every observed 502). So the request never
// executed, which is exactly what the failures showed from the other side: every red found
// the row absent ("Setup failed: card … was never written"), never duplicated. The residual
// risk of a retried write landing twice is therefore accepted deliberately rather than
// overlooked. Note the predicate is about the BODY, not about idempotency — `method` is never
// inspected, and that is on purpose: the measured flake was a POST (`POST /rest/v1/deck`), so
// a GET-only gate would leave it in place.
//
// HOW LOUD A DOUBLE WRITE WOULD BE — MOSTLY, NOT ALWAYS (corrected by impl-review F3,
// 2026-07-30; this paragraph used to say "not a false green" without qualification). Loud for
// the shape actually measured: a duplicated `deck` insert violates `deck_user_name_unique` and
// 409s, and every count / composition oracle in the suite goes red. NOT loud for a card: the
// `flashcard` table carries no uniqueness constraint at all, so a duplicate written by
// `study.test.ts`'s `createNonAcceptedCard` or `candidates.test.ts`'s `seedCard` — neither of
// which is followed by a count assertion — would be silent. The safety argument above is what
// carries those two seams; the 409 is not backing them up.
//
// THE PREDICATE IS DELIBERATELY NARROW — widen it only with the same kind of evidence:
//   - status 502 AND Kong's own upstream wording. No other status is retried: a 500 from an
//     endpoint, a 409, a 4xx refusal and a PostgREST error body are all real signals this
//     suite asserts on, and retrying any of them would mask a genuine failure.
//   - the local stack only (preflight already guarantees the host is 127.0.0.1/localhost).
//   - string or absent bodies only. A `Request` instance or a stream body cannot be replayed
//     without consuming it, so those are passed through untouched rather than guessed at.
//
// It composes with the one file that doubles `fetch`
// (tests/generation/failure-path.test.ts, test-plan §6.9): setup files run first, so the
// `realFetch` that file captures at module scope IS this wrapper, and the Supabase calls it
// delegates get the retry while its own synthetic OpenRouter responses — built above this
// layer, and never a 502 — never reach it.
//
// NOT covered: `globalSetup` (preflight, accounts) runs in a separate process this file
// cannot reach. Left alone on purpose — a 502 there aborts the whole run with its own
// message instead of producing a false green, which is the failure mode that matters.

// The predicate itself lives in `./retry-policy.ts`, pure and exported, so it can be
// asserted (`tests/lib/retry-transport.test.ts`) instead of only reasoned about. This file
// keeps the part that cannot be pure: reading the body and re-issuing the request.
import {
  BACKOFF_MS,
  isKongKeepAliveDrop,
  isLocalStack,
  isReplayableRequest,
  MAX_ATTEMPTS,
  RETRYABLE_STATUS,
} from "./retry-policy";

/**
 * Marks the global as already wrapped.
 *
 * `setupFiles` runs before EVERY test file, so `passthrough` captures whatever is installed
 * at that moment. Today that is always the real `fetch`, because nothing configures
 * `pool`/`isolate` and Vitest's defaults (`pool: "forks"`, `isolate: true`) give each file a
 * fresh global. The day someone sets `isolate: false` / `singleFork`, or runs `--no-isolate`
 * — a natural reflex when debugging exactly the kind of flake this file exists for — each
 * file's setup would capture the PREVIOUS wrapper and they would nest: worst-case attempts
 * become 3^N with compounding backoff, silently. One sentinel closes that, and `Symbol.for`
 * is used rather than a local symbol so the check survives a re-evaluated module registry.
 */
const INSTALLED = Symbol.for("10xcards.retryTransport");

const globals = globalThis as unknown as Record<PropertyKey, unknown>;

const passthrough = globalThis.fetch;

async function bodyTextOf(response: Response): Promise<string> {
  try {
    // `clone()` so the caller still gets an unread body when this turns out NOT to be the
    // flake and the response is handed back as-is.
    return await response.clone().text();
  } catch {
    return "";
  }
}

async function retryingFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  let response = await passthrough(input, init);

  const url = input instanceof Request ? input.url : String(input);
  if (!isLocalStack(url) || !isReplayableRequest(input, init)) return response;

  for (let attempt = 1; attempt < MAX_ATTEMPTS; attempt++) {
    // Status first, and deliberately outside the policy call: cloning and buffering every
    // response body would be a real cost, and only this status can ever match.
    // `isKongKeepAliveDrop` re-checks it so the policy stays complete on its own.
    if (response.status !== RETRYABLE_STATUS) return response;
    if (!isKongKeepAliveDrop(response.status, await bodyTextOf(response))) return response;
    await new Promise((resolve) => setTimeout(resolve, BACKOFF_MS * attempt));
    response = await passthrough(input, init);
  }
  // Three upstream failures in a row is no longer a keep-alive race; hand the 502 back and
  // let the assertion that was in flight report it.
  return response;
}

// Install once, however many times this setup file is evaluated (see INSTALLED above).
if (!globals[INSTALLED]) {
  globals[INSTALLED] = true;
  globalThis.fetch = retryingFetch;
}
